CREATE SCHEMA his;

DROP TABLE IF EXISTS his.patient;
DROP TABLE IF EXISTS his.episode;
DROP TABLE IF EXISTS his.professional;
DROP TABLE IF EXISTS his.center;
DROP TABLE IF EXISTS his.diagnosis;

CREATE TABLE his.diagnosis (
    id INT PRIMARY KEY,
    code VARCHAR(9),
    description VARCHAR(225)
);

CREATE TABLE his.center (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10),
    name VARCHAR(225),
    address VARCHAR(225),
    postal_code VARCHAR(5),
    city VARCHAR(50)
);

CREATE TABLE his.professional (
    id INT PRIMARY KEY,
    name VARCHAR(225),
    lastname VARCHAR(225),
    category VARCHAR(2),
    identifier VARCHAR(11)
);

CREATE TABLE his.patient (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(225),
    lastname VARCHAR(225),
    phone VARCHAR(14),
    address VARCHAR(225),
    city VARCHAR(50),
    email VARCHAR(50),
    nhc VARCHAR(6),
    postal_code VARCHAR(5),
    birth_date DATE,
    dni VARCHAR(9),
    gender VARCHAR(1)
);

CREATE TABLE his.episode (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center VARCHAR(10),
    attended_by INT,
    referred_by INT,
    admitted_by INT,
    origin VARCHAR(1),
    admission_date TIMESTAMP NOT NULL,
    discharge_date TIMESTAMP,
    diagnosis INT NOT NULL,
    patient INT NOT NULL,
    CONSTRAINT fk_referred
        FOREIGN KEY(referred_by)
            REFERENCES his.professional(id)
            ON DELETE SET NULL,
    CONSTRAINT fk_attended
        FOREIGN KEY(attended_by)
            REFERENCES his.professional(id)
            ON DELETE SET NULL,
    CONSTRAINT fk_admitted
        FOREIGN KEY(admitted_by)
            REFERENCES his.professional(id)
            ON DELETE SET NULL,
    CONSTRAINT fk_patient
        FOREIGN KEY(patient)
            REFERENCES his.patient(id)
            ON DELETE CASCADE,
    CONSTRAINT fk_diagnosis
        FOREIGN KEY(diagnosis)
            REFERENCES his.diagnosis(id)
            ON DELETE SET NULL,
    CONSTRAINT fk_center
        FOREIGN KEY(center)
            REFERENCES his.center(code)
            ON DELETE SET NULL
);

INSERT INTO his.patient (name, lastname, phone, address, city, email, nhc, postal_code, birth_date, dni, gender) VALUES ('JUAN', 'LÓPEZ HURTADO', '844324239', 'CALLE SUSPIROS 39 2ºA', 'TERUEL', 'juanitomaravilla@terra.es', '588392', '98345', '1966-11-23', '12345678X', 'M');
INSERT INTO his.patient (name, lastname, phone, address, city, email, nhc, postal_code, birth_date, dni, gender) VALUES ('MARÍA', 'SANZ PEREDA', '369587495', 'AVENIDA LUIS CANDELAS 22 1ºC', 'MADRID', '', '602147', '28056', '1936-04-12', '87654321X', 'F');
INSERT INTO his.patient (name, lastname, phone, address, city, email, nhc, postal_code, birth_date, dni, gender) VALUES ('ALBERTO', 'SOTO OSBORNE', '987090809', 'CALLE LEVANTE 4 2', 'VALLADOLID', 'asoto98@gmail.com', '779032', '47005', '1998-09-09', '01234567A', 'M');

INSERT INTO his.diagnosis VALUES (1, '95.3', 'Esguince auricular');
INSERT INTO his.diagnosis VALUES (2, '152.1', 'Luxación de conjuntiva');
INSERT INTO his.diagnosis VALUES (3, '34.14', 'Irritación de premolar');

INSERT INTO his.center (code, name, address, city, postal_code) VALUES ('HJB','Hospital Juan Blanquín', 'Avenida de los Tilos 30', '43095', 'Santa Cruz de Tenerife');
INSERT INTO his.center (code, name, address, city, postal_code) VALUES ('HLT', 'Hospital La Tregua', 'Calle Muro s/n', '50214', 'Coslada');
INSERT INTO his.center (code, name, address, city, postal_code) VALUES ('CSR', 'Clínica Sagrado Riñón', 'Paseo de la Aragonesa 250', '65677', 'Palamós');

INSERT INTO his.professional VALUES (1, 'DIEGO', 'VILLAR GARCÍA', 'DR', '5502124');
INSERT INTO his.professional VALUES (2, 'SUSANA', 'LAÍNEZ RODRÍGUEZ', 'DR', '6287514');
INSERT INTO his.professional VALUES (3, 'OSCAR', 'LÓPEZ LAMELA', 'DR', '3032001');

INSERT INTO his.episode VALUES (1, 'HJB', 2, 3, 'U', '2023-09-19 08:45:52', NULL, 1, 1);
INSERT INTO his.episode VALUES (2, 'HLT', 3, 2, 1, 'C', '2023-09-19 08:47:12', NULL, 2, 2);
INSERT INTO his.episode VALUES (1, 'CSR', 3, 1, 'H', '2023-09-19 08:49:57', NULL, 3, 3);